### ISSUE TITLE
Parsing error on 'handleRcptToCommand'

### ISSUE THREAD

**Issue by smalot** [SAM-IT/react-smtp#2]
This rcpt should be valid:

````
:<b@b.com>
````

Currently a space is required between `:` and `<`

**Comment by SamMousa** [comment]
Hmm, should multiple spaces be allowed? Your regex allows 0 or more, should it not be 0 or 1? `\s?`

**Comment by SamMousa** [comment]
As far as I can tell the spec doesn't allow for any spaces. I'll merge the request since I think it is better for interoperability
